### PR TITLE
Issue #76 Updated fields in bower.json

### PR DESCRIPTION
**Pull request by arjshiv**
Minor changes to bower.json per official spec

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
Why did you add ```style.css``` to the list of main files?

**Comment by arjshiv** [comment]
So that a WebPack plugin can pull in the default styling when it's '```require```d. It's not critical to this update, so I can remove it if you don't want that to be the default behavior.

**Comment by RandomlyKnighted** [comment]
The styling in ```style.css``` only applies to the examples application. For the main application itself it's not needed.

**Comment by arjshiv** [comment]
Ok, I'll remove it then

**Comment by arjshiv** [comment]
The change has now been made

**Comment by RandomlyKnighted** [comment]
Thank you. Everything looks good. 

@steveathon Everything looks good :shipit:

**Comment by arjshiv** [comment]
Absolutely - glad to help anywhere I can - you have a really useful library!

**Comment by RandomlyKnighted** [comment]
I hope it only gets more useful over the coming months. @steveathon and I have some plans to expand the library very soon.

**Comment by steveathon** [comment]
Thanks team! Looks good. Merged in.

**Pull request merged**
