### PR TITLE
Don't trash placeholder text when initialising

### PR DESCRIPTION
**Pull request by pugnascotia**
I found that if I had a div with a "placeholder" attribute that already contained text, then the content was being trashed. Change the code not to do this!

Also change package.json to list bower and to run bower install as a postinstall.

### CODE REVIEW

**Comment by codewithtyler** [comment]
@RoryHunter can you explain what `"build: "gulp"` does in the package.json?

**Comment by pugnascotia** [comment]
@RandomlyKnighted That just lets me use `npm run build` to execute gulp, since I don't have it globally installed. Hope you don't mind.

**Comment by codewithtyler** [comment]
Would this work with Grunt as well if you had `"build": "grunt"`?

**Comment by pugnascotia** [comment]
Yes - `npm` will find anything in `./node_modules/.bin/` and you can reference it in a `scripts` entry.

**Comment by codewithtyler** [comment]
Interesting, thanks for the clarification. FYI, in a future PR this will change to utilize Grunt over Gulp. However, this is fine for the time being. Thank you for your contribution!

**Pull request merged**
