### PR TITLE
Updated bower.json & adds additional minor fixes

### LINKED ISSUE #8: Adding support for Font Awesome 4.2
I'm adding support for Font-Awesome 4.2. This is a pretty straight forward change but it does break 3.x support because of the change in tags.

### PR DESCRIPTION
**Pull request by RandomlyKnighted**
This PR updates all the dependencies including jQuery, FontAwesome, Bootstrap, and Google Code Prettify. I was able to update and use FontAwesome using bower with no problem so this fix #8 and #9.

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
My latest commit fixes #30.

**Comment by RandomlyKnighted** [comment]
@steveathon is there anything else that I need to do in order to move this PR forward?

**Comment by steveathon** [comment]
Nope - will review and merge today.

**Comment by RandomlyKnighted** [comment]
Thanks by the way, I added a couple of badges to the README to make the releases a bit more obvious.

**Pull request merged**
